- hosts: localhost
  connection: local
  tags: always
  become: true
  tasks:
  - name: install packages
    tags: always
    apt:
      pkg: 
      - curl
  - name: Download my_package
    get_url: 
      url="https://releases.hyper.is/download/deb"
      dest="/home/{{ ansible_env.USER }}/Downloads/hyper.deb"
  - name: Install my_package
    apt: deb="/home/{{ ansible_env.USER }}/Downloads/hyper.deb"
    sudo: true
