- hosts: localhost
  connection: local
  tags: always
  become: true
  tasks:
  - name: install packages
    tags: always
    apt:
      pkg: 
      - curl
  - name: Download hyper
    get_url: 
      url="https://releases.hyper.is/download/deb"
      dest="/tmp/hyper.deb"
  - name: Install hyper
    apt: deb="/tmp/hyper.deb"
