- hosts: localhost
  connection: local
  tags: always
  become: true
  tasks:
  - name: install packages
    tags: always
    apt:
      pkg: 
      - curl
  - name: Download hyper
    get_url: 
      url="https://releases.hyper.is/download/deb"
      dest="/tmp/hyper.deb"
  - name: Install hyper
    apt: deb="/tmp/hyper.deb"
  - name: Download chrome
    get_url: 
      url="https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
      dest="/tmp/google-chrome-stable_current_amd64.deb"
  - name: Install chrome
    apt: deb="/tmp/google-chrome-stable_current_amd64.deb"
  - name: Download vscode
    get_url: 
      url="https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"
      dest="/tmp/vscode.deb"
  - name: Install vscode
    apt: deb="/tmp/vscode.deb"    
